### ISSUE TITLE
Set Custom Offline Message

### ISSUE THREAD

**Issue by ibrahimdevs** [zoho/salesiq-mobilisten-flutter#10]
Hello,

Firstly, there is a method for showing offline status: showOfflineMessage()
I think it's default value should be "true", it is false now and I missed 3 hours before I found this function.
I set business hours on Panel and expected to see any message on my app about non-business hours.

And also, there is customization support for Android with "livechat.messages.offline" key, but there is no support to change it on iOS. If there is a function for setOfflineMessage on Flutter, that will be great.

Thanks,

**Comment by Rishabh-Raghunath** [comment]
Hello @ibrahimdevs, with regards to the [`showOfflineMessage`](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-chat-showOfflineMessage.html) API, the offline banner is enabled by default if the chat waiting time for the brand is not set to infinite. If the chat waiting time for the brand is set to infinite, the banner is disabled by default.

However, we provide you the option to override the defaults and enable(or)disable the offline banner as per your preferences using this API.

With regards to the string customization for the offline banner message, we currently do not have a dart API for the same.
For Android, you can continue using the `livechat.messages.offline` key in the *strings.xml* file.
For iOS, this can be achieved by following the below steps;

Within the **AppDelegate.swift** file, import Mobilisten by adding the `import Mobilisten` statement below the existing module imports. Within the `application(_:didFinishLaunchingWithOptions:)` method, you can add the below snippet of code to customize the string for example.

```swift
ZohoSalesIQ.Chat.setOfflineMessage("We are currently offline. We will get in touch with you shortly.")
```

We request you to try this out and let us know.

**Comment by Rishabh-Raghunath** [comment]
We hope our response was helpful to you. Please feel free to get back to us in case you have further queries.
Thanks.
