### ISSUE TITLE
I want to implement this function

### ISSUE THREAD

**Issue by mdddj** [zoho/salesiq-mobilisten-flutter#12]
中文
当我们回复客户的时候,发送一个URL链接, 客户点击该链接后,在宿主APP中跳转到指定的页面,请问有办法监听到客户点击的某个消息链接吗

English
When we reply to the customer, we send a URL link. After the customer clicks the link, it will jump to the specified page in the host APP. Is there a way to monitor a certain message link clicked by the customer?

**Comment by mdddj** [comment]
![IMG_1677](https://user-images.githubusercontent.com/29020213/161936146-0e7eaff1-d02f-491e-9e72-fdca30c9a057.PNG)

Listen to the user's click on the "URL" message event, and execute the jump in the APP

**Comment by Rishabh-Raghunath** [comment]
Hi @mdddj, Thanks for reaching out.
We are planning to add an option to create a handler for links in one of our upcoming updates.

We will be keeping posted here as soon as the update rolls out.

**Comment by mdddj** [comment]
> Hi @mdddj, Thanks for reaching out. We are planning to add an option to create a handler for links in one of our upcoming updates.
> 
> We will be keeping posted here as soon as the update rolls out.

Okay thank you

**Comment by DavidBhahirathan** [comment]
Hi @mdddj ,

Sorry for the delayed release. We have implemented your above requirement in the latest update. Please check out the version [2.0.0](https://github.com/zoho/salesiq-mobilisten-flutter/releases/tag/v2.0.0). For more details about the implementation please refer to this [documentation](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-event-handler-chatEventChannel.html) with *handleURL* event.

Regards,
Bhahirathan M,
ZohoSalesIQ.
