### ISSUE TITLE
Need support for web platform

### ISSUE THREAD

**Issue by pvsvamsi** [zoho/salesiq-mobilisten-flutter#19]
We are using this plugin for ios, android app and need the support for web platform, as our web app is built on flutter.

**Comment by DavidBhahirathan** [comment]
Hello @pvsvamsi ,

Thanks for writing to us. As of now, we don't have web support for flutter. Please refer to this [documentation](https://help.zoho.com/portal/en/kb/salesiq-2-0/for-administrators/setup-brand/articles/gettingstarted#How_do_I_Log_into_Zoho_SalesIQ) for website integration.

For further queries, please feel free to write us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to assist you.

Regards,
Bhahirathan M.

**Comment by pvsvamsi** [comment]
@DavidBhahirathan The provided documentation doesn't guide us in using the script in a flutter web application. So please guide for the same.

**Comment by DavidBhahirathan** [comment]
Hi @pvsvamsi ,

Please write to us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com) with the Github issue ID to help you further. We'll be happy to assist you.

Thanks.

**Comment by aytunch** [comment]
Our company is using Flutter for iOS, Android and web also. we really wished this plugin was made in to a federated one and can support web. Otherwise our codebase will have too many complications and maintanence/versioning problems. This is the biggest strength of Flutter, why does ZOHO not considering adding web support for this package? It shouldn't be hard.

**Comment by DavidBhahirathan** [comment]
Hello,

We plan to add web support for Flutter, but it is not currently on our immediate roadmap. We will keep you updated on the progress of this feature and notify you once it is released.

Thank you for your patience and understanding.

Best regards,
Bhahirathan,
Zoho SalesIQ.
