### ISSUE TITLE
App lifecycle + Theme customization for Android 

### ISSUE THREAD

**Issue by aelhag** [zoho/salesiq-mobilisten-flutter#24]
I have two issues:
1. Whenever a user clicks on the "back" button after spending some time chatting with an agent, the app will restart from the splash screen again because it was killed in the background. Is there a way to prevent this from happening?
2. I was unable to find a way to customize the Android App bar theme colors in Flutter ! is there any way to do it?

**Comment by DavidBhahirathan** [comment]
Hi @aelhag ,

Thanks for writing to us. We have found a fix for the first issue and will roll it out shortly. We'll update you once it's out. 

For the second issue, please add the below attributes in the SalesIQ theme.

1. siq_toolbar_backgroundcolor - the color of the App bar.
2. siq_forms_toolbar_backgroundcolor- the color of the App bar on the traditional page.

Sample code:
```
<!--  Thie below theme will be used, when the device is in dark mode  -->
<style name="Theme.SalesIQ.Base.Dark" parent="Theme.SalesIQ.Dark" >
            <item name="siq_toolbar_backgroundcolor">#0000ff</item>
            <!-- below one is used to change the toolbar color in traditional form page -->
            <item name="siq_forms_toolbar_backgroundcolor">#0000ff</item>
</style>

<!--  The below theme will be used, when the device is in dark mode  -->
<style name="Theme.SalesIQ.Base.DarkActionBar" parent="Theme.SalesIQ.Light" >
            <item name="siq_toolbar_backgroundcolor">#00ff00</item>
            <!-- below one is used to change the toolbar color in traditional form page -->
            <item name="siq_forms_toolbar_backgroundcolor">#00ff00</item>
</style>
```
Please refer to this [documentation](https://www.zoho.com/salesiq/help/developer-guides/android-mobile-sdk-theme-customization-launcher-2.0.html) for more customizations.

For further queries, please feel free to write us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to assist you.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by aelhag** [comment]
Thanks @DavidBhahirathan for the reply,

Regarding the second issue, where to find the SalesIQ theme, I would appreciate it if you could share me the path in Flutter where I can find the SalesIQ theme file to add the attributes, also do i need to add `ZohoSalesIQ.syncThemeWithOS(false)` to opt-out from default system device theme, if yes, then the method 'syncThemeWithOS' isn't defined for the type 'ZohoSalesIQ' in your flutter package.

Looking forward for the update...

Best Regards,

**Comment by simonpham** [comment]
@aelhag @DavidBhahirathan 

I also have Back button issue when open the chat from push notification

**Comment by DavidBhahirathan** [comment]
Hi @aelhag and @simonpham ,

As mentioned in the previous comment, the first back button issue has been fixed, and it'll be rolled out shortly. 

Regarding the second issue, Please follow the below steps:
1. Create a styles.xml file under res/values if it does not exists in our android source directory.
2. Then add the styles script mentioned in the previous comment.

Regarding the ZohoSalesIQ.syncThemeWithOS() API. we are implementing it in our current development. We'll let you know once it's live.

Regards,
Bhahirathan M,
ZohoSalesIQ.

**Comment by DavidBhahirathan** [comment]
Hi @simonpham and @aelhag ,

Thanks for your patience. The syncThemeWithOSForAndroid() API has been implemented in the latest update. Please check out the version [2.0.0](https://github.com/zoho/salesiq-mobilisten-flutter/releases/tag/v2.0.0).

*API*
```
ZohoSalesIQ.syncThemeWithOSForAndroid(true/false);
```

styles.xml
```
<!-- Below is the sample XML code for styles -->

<!--  This works, if syncThemeWithOSForAndroid is set as false for both light and dark mode -->
<style name="Theme.SalesIQ.Base" parent="Theme.SalesIQ.Base.DarkActionBar" >
            <item name="siq_toolbar_backgroundcolor">#ff0000</item>
            <item name="siq_forms_submitbutton_backgroundcolor">#ff0000</item>
            <item name="siq_forms_toolbar_backgroundcolor">#ff0000</item>
        </style>

<!--  This works, if syncThemeWithOSForAndroid is set as true when the device is in dark mode  -->
<style name="Theme.SalesIQ.Base.Dark" parent="Theme.SalesIQ.Dark" >
            <item name="siq_forms_submitbutton_backgroundcolor">#0000ff</item>
            <item name="siq_toolbar_backgroundcolor">#0000ff</item>
            <item name="siq_forms_toolbar_backgroundcolor">#0000ff</item>
</style>
<!--  This works, if syncThemeWithOSForAndroid is set as true when the device is in light mode  -->
<style name="Theme.SalesIQ.Base.DarkActionBar" parent="Theme.SalesIQ.Light" >
            <item name="siq_forms_submitbutton_backgroundcolor">#00ff00</item>
            <item name="siq_toolbar_backgroundcolor">#00ff00</item>
            <!-- below one is used to change the toolbar color in traditional form page -->
            <item name="siq_forms_toolbar_backgroundcolor">#00ff00</item>
</style>

```
For further queries, please feel free to write us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to assist you.

Regards,
Bhahirathan M,
ZohoSalesIQ.

**Comment by akshayam01** [comment]
Hello,
is there an option to implement syncthemewithos for iOS?
@bhahirathan-mb-11956

**Comment by venkatesh-ramesh-12517** [comment]
Hello @akshayam01 

Thank you for reaching out. Currently, we provide theme options for iOS UI customization. Visit our help documentation for guidance on implementing themes:

[Zoho SalesIQ - Flutter SDK UI Customization](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-ui-customization.html)

Additionally, you can implement the theme using Asset Color Names for your request. This allows you to use color names defined in your asset catalog, which can adapt seamlessly to light and dark modes, enabling the app to sync with the system theme.

I hope this helps. Please feel free to reach out to us at (support@zohosalesiq.com) for further assistance.

Best regards,
Venkatesh | Zoho SalesIQ

**Comment by akshayam01** [comment]
Hey @venkatesh-ramesh-12517 
I want to turn off the sync with os option for iOS 
As I dont want the user's os mode to effect the colours
