### ISSUE TITLE
Enhancement: Event to track changes to the unread message count

### ISSUE THREAD

**Issue by ibrahimdevs** [zoho/salesiq-mobilisten-flutter#3]
Hi,
I want to design my own launcher button. I can open Mobilisten with invoking the ZohoSalesIQ.show() method. 
But default launcher button, there is a chat counter badge, so user can understand there is a waiting chat there.
I want to put this feature to my custom launcher button. Is there any listener like new chat response come?
I tried:
```
 ZohoSalesIQ.eventChannel.listen((event) {
 });
```
But this channel not triggered when new message come. Actually plugin provides in-app notification to show new coming message, it would be very helpful that you can put listener and triger it there.

**Comment by Rishabh-Raghunath** [comment]
Hello @ibrahimdevs, we currently do not have an event to track changes to the unread count in the plugin.
We shall definitely look into adding an event for the same in the next update.

**Comment by Angu-G** [comment]
Hello @ibrahimdevs, Thank you for your patience. We have supported an event to track changes to the unread count in the plugin. You can refer to more about the event and the method to fetch the unread count in our [release notes](https://github.com/zoho/salesiq-mobilisten-flutter/releases/tag/v1.0.2). You can check and acknowledge back to us.

**Comment by ibrahimdevs** [comment]
@Angu-G thanks for this feature. I checked it, it looks working perfect!
