### ISSUE TITLE
Launcher properties for Android only changes floating/static modes but documentation shows more properties

### ISSUE THREAD

**Issue by ashishbeck** [zoho/salesiq-mobilisten-flutter#39]
Currently, the launcher properties do have properties for changing the y position, icon, and horizontal or vertical pinning. But they are inaccessible and there's no way actually to configure them. The snippet inside the SDK can be found in `lib/launcher.dart` and is as follows.
```
class LauncherProperties {
  LauncherMode mode = LauncherMode.floating;
  int? y;
  String? icon;
  Horizontal? horizontalDirection;
  Vertical? verticalDirection;
  LauncherProperties(LauncherMode launcherMode) {
    mode = launcherMode;
  }
}
```

I am sure there must be some development going on for this. Do we have a timeline on when we can expect to see this change in the upcoming releases?

And also, there isn't anything equivalent for iOS from my exploration thus far.

**Comment by DavidBhahirathan** [comment]
Hi @ashishbeck,

Thank you for contacting us. Please refer to this [documentation](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-launcher-button-customization.html) for instructions on customizing the launcher. If you need to change the position of the launcher, make sure to pass the mode as "floating" for LauncherProperties.

If you encounter any issues with the implementation, please email us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com) with your GitHub ID included.

Best regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by ashishbeck** [comment]
Thanks for the response. What is an excellent way to make the floating launcher about 50 pixels from the bottom?

From what I can see, we can set the `y` value only when it is floating at the top. And the value of `y` is not the same as logical pixels. Can you explain what the unit of `y` is?

Thanks!

**Comment by ashishbeck** [comment]
Yes, that is a great working example. In order to make the final value respect flutter's screen size, we can modify the last line like this:
```dart
launcherProperties.y = fullScreenHeight - (50 * mediaQueryData.devicePixelRatio).toInt();
```

Thanks for the help. Closing it.
