### ISSUE TITLE
Android Release Mode issue with chat

### ISSUE THREAD

**Issue by ivangoluuk** [zoho/salesiq-mobilisten-flutter#44]
There is a chat issue with android in release mode but no in debug mode . Is there a different configuration between debug and release mode ?

Why in Release mode, Messages in chat  appear as sent by the bot and not by the user?

**Comment by ivangoluuk** [comment]
![IMG_0035](https://github.com/zoho/salesiq-mobilisten-flutter/assets/107516247/8f9f0930-f7fa-4442-b57d-4e9f82208509)

**Comment by DavidBhahirathan** [comment]
Hi @ivangoluuk ,

Thanks for writing to us. We'll look into this issue and update you here once resolved.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by ivangoluuk** [comment]
Thank u 🙏🏻

**Comment by DavidBhahirathan** [comment]
Hi @ivangoluuk ,

Thank you for your patience. We have fixed this issue. We recommend you update to the latest version [3.1.0](https://github.com/zoho/salesiq-mobilisten-flutter/releases/tag/v3.1.0), and verify. Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.

Regards,
Bhahirathan M
Zoho SalesIQ.
