### ISSUE TITLE
ZohoSalesIQ.setVisitorName doesn't work on android

### ISSUE THREAD

**Issue by widiastika97** [zoho/salesiq-mobilisten-flutter#52]
I use the setVisitorName function but the name that appears does not match what I set,

as an example :
I put the value 'andru darusman'
and email 'avina@mail.com'
but what is input in the visitor name is 'avina'

**Comment by DavidBhahirathan** [comment]
Hi @widiastika97 ,
We apologize for the inconvenience caused. We'll look into this issue and update you once it's fixed.

Thanks,
Bhahirathan M
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @widiastika97 ,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [5.0.0](https://github.com/zoho/SalesIQ-Mobilisten-flutter/releases/tag/v5.0.0), and verify. Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.

Regards,
Bhahirathan M
Zoho SalesIQ.
