### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zoho/livechat/android/ZohoLiveChat$Chat;

### ISSUE THREAD

**Issue by Oyedee** [zoho/salesiq-mobilisten-flutter#55]
The app crashes on Android when launched. 

<img width="1813" alt="image" src="https://github.com/zoho/salesiq-mobilisten-flutter/assets/24321091/a8127f46-aff7-4552-87d6-0f734329366b">

**Comment by bhahirathan-mb-11956** [comment]
Hi @Oyedee,

We apologize for any inconvenience caused. Unfortunately, we are unable to reproduce the mentioned crash. However, we have implemented changes that resemble the scenario you described.

We suggest you update SDK to version [5.0.0](https://github.com/zoho/SalesIQ-Mobilisten-flutter/releases/tag/v5.0.0) and check if the issue persists. If it does, please feel free to write back to us at (support@zohosalesiq.com). We will investigate this further. 

Best regards,
Bhahirathan M.

**Comment by Oyedee** [comment]
Upgrading to version 5.0.0 fixed the issue. 

Thanks for the response.
