### ISSUE TITLE
Unable to Retrieve Chat Status for Action Execution

### ISSUE THREAD

**Issue by mratanpara** [zoho/salesiq-mobilisten-flutter#58]
Currently, I'm encountering an issue where I'm unable to determine the status of a chat session, whether it's open or closed. This poses a problem as I need to perform specific actions when a chat closes, but without knowing its status, I'm unable to execute these actions effectively. 

It would be immensely helpful to have a feature or functionality implemented that provides clear indicators of chat status, enabling me to initiate actions promptly upon chat closure.

Plugin version:
`salesiq_mobilisten: ^4.0.0`

Thank you in advance for any help.

**Comment by bhahirathan-mb-11956** [comment]
Hi @mratanpara,

Thanks for writing to us. Our platform features an [event channel](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-event-handler-chatEventChannel.html) for chat events, broadcasting all chat-related activities in real-time. Additionally, our [getChats()](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-chat-getchats.html) API allows you to access all the conversations and their respective details. Please explore these APIs to fit your business needs.

Regards,
Bhahirathan M,
Zoho SalesIQ.
