### ISSUE TITLE
The app crashes when i start sending message to zoho.

### ISSUE THREAD

**Issue by abdelrahmanhegazy1** [zoho/salesiq-mobilisten-flutter#59]
the error comes from salesIq_mobilisten_sdk 
E/AndroidRuntime( 7322): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.zoho.livechat.android.models.SalesIQChat.getVisitid()' on a null object reference
E/AndroidRuntime( 7322): 	at com.zoho.livechat.android.utils.LiveChatUtil.getVisitorChatObject(LiveChatUtil.java:2511)
E/AndroidRuntime( 7322): 	at com.zoho.livechat.android.utils.LiveChatUtil$2.run(LiveChatUtil.java:2696)
E/AndroidRuntime( 7322): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 7322): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7322): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 7322): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 7322): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 7322): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7322): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 7322): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process ( 7322): Sending signal. PID: 7322 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by bhahirathan-mb-11956** [comment]
Hi @abdelrahmanhegazy1 ,

We apologize for the inconvenience caused. We'll look into this crash and update you. Meanwhile, please confirm that this crash is happening in the latest version of the SDK. 

Please write to us at support@zohosalesiq.com along with your portal details and chat ID so we can investigate this crash further. 

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by abdelrahmanhegazy1** [comment]
> Hi @abdelrahmanhegazy1 ,
> 
> We apologize for the inconvenience caused. We'll look into this crash and update you. Meanwhile, please confirm that this crash is happening in the latest version of the SDK.
> 
> Please write to us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com) along with your portal details and chat ID so we can investigate this crash further.
> 
> Regards, Bhahirathan M, Zoho SalesIQ.

yes the crash happened in the latest version of the SDK. specifically in Android Platform. i didn't get the chat id because it crash when the message sent to zoho.

**Comment by abdelrahmanhegazy1** [comment]
is there any update?

**Comment by Zubairpv** [comment]
hi @bhahirathan-mb-11956 is there any update
my app crash when i start send message in zoho

E/AndroidRuntime(13096): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
E/AndroidRuntime(13096): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
E/AndroidRuntime(13096): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
E/AndroidRuntime(13096): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
E/AndroidRuntime(13096): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@927fc5d, Dispatchers.IO]
I/Process (13096): Sending signal. PID: 13096 SIG: 9
Lost connection to device.

**Comment by bhahirathan-mb-11956** [comment]
Hi @Zubairpv 

We apologize for the inconvenience. As mentioned before, we are actively working to fix the app crash issue. As an update, it is currently in the testing phase and will be available soon. I'll keep you posted on the same regarding the updates.

**Comment by bhahirathan-mb-11956** [comment]
Hi @abdelrahmanhegazy1 and @Zubairpv ,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [6.1.0](https://github.com/zoho/SalesIQ-Mobilisten-flutter/releases/tag/v6.1.0), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M,
Zoho SalesIQ.
