### ISSUE TITLE
Stuck at the function ZohoSalesIQ.setLanguage

### ISSUE THREAD

**Issue by philipvu30** [zoho/salesiq-mobilisten-flutter#6]
Hi,

I have an issue with this function. I made a test button like this - [https://snipboard.io/aFKOXb.jpg](https://snipboard.io/aFKOXb.jpg)
And the ZohoSalesIQ.show() can't be reached. It's just stuck at ZohoSalesIQ.setLanguage
If I remove the await for the setLanguage function, the chat window will show up as Right to Left with English version.
I have tried with other language codes as well, but it seems it does not work.
Could you please have a check?

Thank you.

**Comment by Angu-G** [comment]
Hello @philipvu30, Can you please trigger the **setLanguage()** API after **init()** call and have a check? In general, show() API shall be triggered separately.

**Comment by philipvu30** [comment]
Hi,

Thank you for the response.
If I create a new project, it works just fine.
But on my current project, it's not working.
May I ask what is the requirement for this package?

**Comment by Angu-G** [comment]
Hi @philipvu30, 
For Android - **minSdkVersion 14** and above is required
For iOS, **iOS 10 or above** is required. The minimum version of Xcode required is **Xcode 12**.

 You can also refer to the requirements for this package in our help [documentation](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-installation.html).

**Comment by Angu-G** [comment]
Hello @philipvu30, Hope the answers provided are helpful. We are closing this issue now. You can get back to us anytime.
