### ISSUE TITLE
On the Android platform, executing functions will permanently block

### ISSUE THREAD

**Issue by mdddj** [zoho/salesiq-mobilisten-flutter#64]
```yaml
salesiq_mobilisten: ^6.2.0
```
example 
```dart
void testSM(){
      debugPrint("start register visitor");
      await ZohoSalesIQ.registerVisitor(id);
      /// --------
      debugPrint("This sentence will never be executed");
}
```

If you delete 'await', it is valid

**Comment by bhahirathan-mb-11956** [comment]
Hi @mdddj,
 
We apologize for the inconvenience. We will look into this issue and update you. Meanwhile, please use the API as given in the snippet below and try it one more time.
 
```
ZohoSalesIQ.registerVisitor("visitor_unique_id").then((result){
      // Registration successful
}).catchError((error, stackTrace) => {
      // Registration failed
});
```
 
Best regards,
Bhahirathan M
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @mdddj ,
 
Thank you for your patience. We have fixed issues related to the API you have mentioned, and we also recommend you check whether you're using the [registerVisitor](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-visitor-registerVisitor.html) and [unregisterVisitor](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-visitor-unregisterVisitor.html) API on the success callback your user login and logout respectively.
 
We recommend you update to the latest version [6.3.1](https://github.com/zoho/SalesIQ-Mobilisten-flutter/releases/tag/v6.3.1), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.
 
Regards,
Bhahirathan M
Zoho SalesIQ.
