### ISSUE TITLE
How skip the default SDK conversations list when navigating back from conversation

### ISSUE THREAD

**Issue by AlaaCherbib** [zoho/salesiq-mobilisten-flutter#67]
Hello, In the app I use 
`List<SIQChat> siqChats = await ZohoSalesIQ.getChats();`
to get the chats and show my own custom conversations list.

However when I navigate to a specific chat using
`ZohoSalesIQ.openChatWithID(chatID);`

and then navigate back, it goes back to the SDK conversations list, then I have again to tap on the back button to get to my custom list.

Is there a way to immediately dismiss the SDK when the user taps on the back button on the conversation screen and skip showing the SDK conversations list?

**Comment by bhahirathan-mb-11956** [comment]
Hi @AlaaCherbib,
 
Thanks for writing to us. To turn off the conversation history, please set it to false with [ZohoSalesIQ.setConversationVisibility()](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-conversation-setConversationVisibility.html) API.
 
I hope this helps. If you have any other queries, please write us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to help with this case.
 
Best regards,
Bhahirathan M
Zoho SalesIQ.

**Comment by AlaaCherbib** [comment]
Hi @bhahirathan-mb-11956 , Thanks for your feedback. It looks good I think, the conversations list is not shown anymore.
