### ISSUE TITLE
Is there a way to prevent the users from ending the chat?

### ISSUE THREAD

**Issue by AlaaEddineCharbib** [zoho/salesiq-mobilisten-flutter#68]
Some of my users sometimes end the chat and I am unable to respond to them, especially when they are anonymous users and I have no email address in their info. I believe they do that by mistake or do now know that clicking on end chat closes the chat completely and prevent the support team from answering. It results in bad reviews on the Appstore afterwards.

Is there a possibility to disable the user from ending the chat?

Thanks.

**Comment by bhahirathan-mb-11956** [comment]
Hi @AlaaEddineCharbib,
 
Thanks for writing to us. We have already worked on this requirement and the changes are under in testing phase now. We will keep you posted on our progress.
 
Regards,
Bhahirathan M
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @AlaaEddineCharbib ,
 
Thanks for your patience. We have supported changing the visibility of the end chat option.
 
Please check the below sample snippet:
1. `ZohoSalesIQ.chat.setVisibility(ZSIQChatComponent.end, false);` - hides the end chat option always(This has the highest priority over the below configurations).
2. `ZohoSalesIQ.chat.setVisibility(ZSIQChatComponent.endWhenInQueue, false);` - hides end chat option only when in the queue.
3. `ZohoSalesIQ.chat.setVisibility(ZSIQChatComponent.endWhenBotConnected, false);` - hides the end chat option only for the chats that are connected to the bot.
4. `ZohoSalesIQ.chat.setVisibility(ZSIQChatComponent.endWhenOperatorConnected, false);` - hides the end chat option only for the chats that are connected to the operator.
 
I hope this helps. Please feel free to write back to us at (support@zohosalesiq.com) in case of any queries.
 
Regards,
Bhahirathan M
Zoho SalesIQ.
