### ISSUE TITLE
 Unhandled Exception: PlatformException(615, invalid visitor id, null, null)

### ISSUE THREAD

**Issue by mdddj** [zoho/salesiq-mobilisten-flutter#7]
Unable to register guest

```dart
  /// 绑定客服ID
  /// bind
  void bindKfId(UserModelV2 user) {

    try{
      logger('绑定用户客服ID：${user.kfId}');
      // U-1679091C5A880FAF6FB5E6087EB1B2DC
      ZohoSalesIQ.registerVisitor(user.kfId).then((value) {
        /// 更新未读消息列表。
        AppController.instance.updateImUnreadCount();
      });

      ZohoSalesIQ.setVisitorAddInfo("Email", user.email ?? "未获取");
      ZohoSalesIQ.setVisitorAddInfo("CustomerId", '${user.id}');
      ZohoSalesIQ.setVisitorEmail(user.email ?? '未获取');
      ZohoSalesIQ.setVisitorName('${user.firstname} ${user.lastname}');

      logger('在线客服服务器已开启。end');
    }catch(e){
      loggerE(e);
    }
  }
```
![image](https://user-images.githubusercontent.com/29020213/149092443-b4980b49-ff5f-461c-856c-c0e993e0cce0.png)

output
![image](https://user-images.githubusercontent.com/29020213/149092331-ecfc0a49-7b4e-40f5-a8de-0496e493b8e4.png)

```dart
E/flutter (12963): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(615, invalid visitor id, null, null)
E/flutter (12963): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (12963): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (12963): <asynchronous suspension>
E/flutter (12963): #2      ZohoSalesIQ.registerVisitor (package:salesiq_mobilisten/salesiq_mobilisten.dart:82:12)
E/flutter (12963): <asynchronous suspension>
E/flutter (12963): 
```
我觉得可以添加一些API, 可以检测是否已经注册访客,或者获取当前注册访客的ID. 这样将会很有帮助.谢谢
-------en-------
I think it's possible to add some API that can detect if a visitor is already registered, or get the ID of the currently registered visitor. This will be helpful. Thanks

**Comment by Angu-G** [comment]
Hi @mdddj, Thanks for your patience. The error will be thrown only when an invalid ID is passed. The ID you have specified in the comment should be valid. Can you please check once the same id has been passed from your end? Also, let us know the place where the registerVisitor() is triggered (like after init() API call).
