### ISSUE TITLE
Android Build Fails Due to Deprecated API and Unsafe Operations in R8 build

### ISSUE THREAD

**Issue by mohamedshasho** [zoho/salesiq-mobilisten-flutter#70]
Hello,
I encountered several issues while building my Flutter app using the salesiq_mobilisten library (version 6.3.0):

```
Deprecated API: Some input files use or override deprecated APIs. Here's the specific file:

MobilistenPlugin.java (path: C:\Users\Dell\AppData\Local\Pub\Cache\hosted\pub.dev\salesiq_mobilisten-6.3.0\android\src\main\java\com\zohosalesiq\plugin\MobilistenPlugin.java)
```

Build Failure Message:
```

FAILURE: Build failed with an exception.
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in E:\work\projects\w-mobile\build\app\outputs\mapping\release\missing_rules.txt.                                                                                                  Chat$Department and 4 other contexts)celize.Parcelize (referenced from: com.zoho.livechat.android.modules.notifications.sdk.entities.SalesIQNotificationPayload$C

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

```

What was in missing_rules.txt 
`-dontwarn kotlinx.parcelize.Parcelize
`
Gradle:
```
id "com.android.application" version '8.3.0' apply false
id "org.jetbrains.kotlin.android" version "1.9.10" apply false
```

Please advise on how to resolve these deprecated API and unsafe operation issues, and any additional steps to fix the R8 build failure. Thank you!

**Comment by bhahirathan-mb-11956** [comment]
@mohamedshasho , As there hasn't been any recent activity, we're closing this issue for now. If you need further assistance or would like us to revisit this, please don't hesitate to let us know, and we'll be happy to reopen it. In the meantime, check out our [latest release](https://github.com/zoho/salesiq-mobilisten-flutter/releases/latest).
 
Thank you for understanding. Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.
