### ISSUE TITLE
Enhancement: Customization Features

### ISSUE THREAD

**Issue by ibrahimdevs** [zoho/salesiq-mobilisten-flutter#8]
Hello @Rishabh-Raghunath ,

We need customization feature for Android;
- Most importantly: Change Color. There is a method for iOS : setThemeColorForiOS, but there is no method for Android.

Other Customizations for both Android & iOS:
1. Change Description text.
2. Change Start Chat text.
3. Change Messages tab text.
4. Change FAQs tab text.

![Screenshot_20220225-164515](https://user-images.githubusercontent.com/2773578/155726661-e2790ae7-46aa-4105-961d-32dc3cef62b3.png)

Thanks,

**Comment by Angu-G** [comment]
Hi @ibrahimdevs, 
> We need customization feature for Android;

We do have support and you can refer to our customization help [doc](https://www.zoho.com/salesiq/help/developer-guides/android-mobile-sdk-theme-customization-2.0.html) for whole theme changes and component-level customizations. 


> Other Customizations for both Android & iOS:

### **For Android:**
We do have a separate section for strings customization [Reference link](https://www.zoho.com/salesiq/help/developer-guides/android-mobile-sdk-theme-customization-strings-2.0.html). You can customize the strings inside **strings.xml**.
1. Change Description text.
    Component name - livechat.conversation.emptystate
     **Example**:  `<string name="livechat.conversation.emptystate"> Your own content </string>`

2. Change Start Chat text.
    Component name - livechat.conversation.startchat
     **Example**:  `<string name="livechat.conversation.startchat"> Your own content </string>`

3. Change Messages tab text.
     Component name - livechat.conversation.title
     or
     You can also make use of our internal API [.setConversationListTitle](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-conversation-setConversationListTitle.html).

4. Change FAQs tab text. 
     Component name - livechat.article.title
     or
     You can also customize this string at the portal level. Settings > Brands > {Brand name} > Personalisation > **Specify a name for the knowledge base in visitor chat windows**

### **For iOS:**
1. Change Description text.
     This is currently not supported in iOS but we have this coming in our roadmap.

2. Change Start Chat text.
     This is currently not supported in iOS but we have this coming in our roadmap.

3. Change Messages tab text.
     You can make use of our internal API [.setConversationListTitle](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-conversation-setConversationListTitle.html).

4. Change FAQs tab text. 
     You can customize this string at the portal level. Settings > Brands > {Brand name} > Personalisation > **Specify a name for the knowledge base in visitor chat windows**.

**Comment by ibrahimdevs** [comment]
@Angu-G thanks for your detailed response.

1. It is better, If you could add these customization options to Flutter documentation (https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-installation.html) At least a description and redirection to links.
2. Android - 2 - "livechat.conversation.startchat" not affecting.
3. Android - 4 - "livechat. article. title" not affecting.
4. I'm waiting for iOS 1 & 2.
5. iOS 4 - it is better to provide another option to set this text. Because we need multi-language support, if we change it from dashboard, there is no multi-language support.

**Comment by venkatesh-ramesh-12517** [comment]
Hello @ibrahimdevs 

We have reviewed and updated your recent requests. Please find the details and solutions below:
 
### 1. Android - 2 and 4:
- The issues have been fixed. Please update to the latest version of [6.1.0](https://github.com/zoho/salesiq-mobilisten-flutter/releases/tag/v6.1.0) and use the same key.
- For Android - 4, you can customize the title from the portal:
Settings -> Brands -> Personalization -> Knowledgebase -> Tab Name
 
### 2. iOS - 1 and 2:
- For iOS 1 and 2, please refer to the following API documentation to customize the title as needed:
[.registerLocalizationFileForiOS()](https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-register-localization-file-ios.html)
 
### 3. iOS - 4:
- If you want to customize the knowledge base tab title with multilingual support, you can set it from the portal with the corresponding languages:
 Settings -> Brands -> Personalization -> Knowledgebase -> Tab Name -> Translate Name
 
I hope this helps. Please feel free to write back to us at (support@zohosalesiq.com) in case of any queries.
 
Regards,
Venkatesh R
Zoho SalesIQ.
