### ISSUE TITLE
Android Version Push Notification Support

### ISSUE THREAD

**Issue by ibrahimdevs** [zoho/salesiq-mobilisten-flutter#9]
Hello @Angu-G,

Is there any push notification support for Android ? There is a method for iOS "enablePushForiOS" but there is no method for Android. How can I enable push notification support for Android?

* I've already added Server Key to Settings > Brands > Installation > Android > Configure push notifications section.

Thanks,

**Comment by Angu-G** [comment]
Hello @ibrahimdevs, Yeah if you have added the server key and followed the steps in our help doc you can make use of the PN support. No need for any APIs to enable in Android.

**Comment by faithomotoso** [comment]
Hi @Angu-G , just want to say it'll be nice to have one for Android. I have an app that a user has to log in to and I'm unable to explicitly the method to `enablePush` when they log in, at the moment I always call the method when the push token changes or manually when the app is launched.

**Comment by teewhydope** [comment]
try this @faithomotoso, pass the token from flutter side

    private fun mobileListenMethodChannel(flutterEngine: FlutterEngine) {
        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            mobilistenMethodChannel,
        ).setMethodCallHandler { call, result ->
            when (call.method) {
                "enablePushForAndroid" -> {
                    val token = call.argument("token") ?: ""
                    if(token.isNotEmpty()) {
                        MobilistenPlugin.enablePush(token, true)
                    }
                }
            }
        }
    }
